const en = {
  tagline: 'Agentic AI runtime for modern conversation surfaces, built in Rust.',
  description: 'MicroClaw is a Rust-first agent runtime for multi-channel automation with tools, memory, scheduling, and MCP federation.',
  eyebrow: 'RUST AGENT RUNTIME',
  heroTitle: 'Build one agent core. Deploy it to every conversation surface.',
  heroText: 'MicroClaw gives teams tool-using automation with durable memory, resumable sessions, subagents, and channel adapters that never fork core business logic.',
  start: 'Start in 5 Minutes', github: 'View GitHub', meta: ['Single Service', 'SQLite Persistence', 'ACP + MCP + Skills'],
  quickstart: 'Quickstart', copy: 'Copy', copied: 'Copied',
  installLabels: {script: 'Install Script', brew: 'Homebrew', cargo: 'Cargo', powershell: 'PowerShell Script'},
  installHints: {macScript: 'Recommended for most macOS setups', brew: 'Best for Homebrew-based workflows', source: 'Build from source with the Rust toolchain', windowsScript: 'Recommended for native Windows installs', linuxScript: 'Recommended for most Linux setups'},
  proof: [
    ['Architecture', 'Channel-independent core with adapter-based delivery'],
    ['Memory', 'AGENTS.md and structured SQLite memory with observability'],
    ['Execution', 'Tool loop, native and ACP subagents, scheduling, and background work'],
    ['Extensibility', 'Skills catalog and MCP tool federation'],
  ],
  whyTitle: 'Why teams choose MicroClaw',
  whyText: 'A runtime-centered stack that keeps your logic stable while channels, models, and tools evolve.',
  capabilities: [
    ['Channel-Independent Core', 'One shared agent loop drives every chat and Web adapter.'],
    ['Tool-Using Agent Loop', 'The model chains tools across multiple steps until the task is complete.'],
    ['Concurrent Specialist Team', 'Named specialist subagents can work concurrently, natively or through ACP workers.'],
    ['Memory With Quality Gates', 'File and structured SQLite memory include extraction, deduplication, and lifecycle controls.'],
    ['Skills + MCP', 'Built-in skills and external MCP servers extend the runtime without changing the core loop.'],
    ['Operational Visibility', 'Usage, memory observability, config checks, metrics, and traces make drift visible.'],
    ['Scheduler + Background Tasks', 'Recurring and one-shot tasks run through the same runtime.'],
  ],
  architectureTitle: 'Runtime architecture at a glance',
  architectureText: 'The same engine powers every conversation, wherever users talk to the agent.',
  architectureAlt: 'MicroClaw architecture overview',
  architectureSteps: [
    ['Ingest', 'Channel adapters normalize incoming events into one runtime format.'],
    ['Assemble Context', 'Session state, memory, and active skills are loaded.'],
    ['Reason + Tools', 'The provider layer streams model output and tool calls through a controlled loop.'],
    ['Persist + Reflect', 'Sessions and memories are persisted, then durable facts are updated.'],
    ['Deliver', 'Results are split to channel limits and delivered with consistent semantics.'],
  ],
  useCasesTitle: 'Use MicroClaw for real workloads',
  useCasesText: 'From individual operators to platform teams, one runtime covers multiple paths.',
  useCases: [
    ['Personal Infrastructure Agent', 'Run one assistant across chats with memory, scheduling, and shell or file tools.'],
    ['Team Operations Bot', 'Use permission-aware tools and session history for recurring internal workflows.'],
    ['Product Prototyping Runtime', 'Ship new channels and tools on one Rust core instead of fragmented bots.'],
  ],
  readDetails: 'Read implementation details',
  ctaTitle: 'Ship a production-grade Rust agent stack.',
  ctaText: 'Start with setup, then explore tools, permissions, memory, and channel deployment.',
  quickstartCta: 'Quickstart', architectureDocs: 'Architecture Docs', toolsReference: 'Generated Tools Reference',
}

const translations = {
  en,
  'zh-CN': {
    tagline: '用 Rust 构建、面向现代对话入口的智能体运行时。', description: 'MicroClaw 是一个 Rust 优先的多渠道智能体运行时，具备工具、记忆、调度和 MCP 联邦能力。', eyebrow: 'RUST 智能体运行时', heroTitle: '只构建一套智能体核心，部署到所有对话入口。', heroText: 'MicroClaw 为团队提供工具执行、持久记忆、可恢复会话、子智能体和不复制核心业务逻辑的渠道适配器。', start: '5 分钟开始', github: '查看 GitHub', meta: ['单一服务', 'SQLite 持久化', 'ACP + MCP + 技能'], quickstart: '快速开始', copy: '复制', copied: '已复制',
    installLabels: {script: '安装脚本', brew: 'Homebrew', cargo: 'Cargo', powershell: 'PowerShell 脚本'}, installHints: {macScript: '推荐用于大多数 macOS 环境', brew: '适合使用 Homebrew 的工作流', source: '使用 Rust 工具链从源码构建', windowsScript: '推荐用于原生 Windows 安装', linuxScript: '推荐用于大多数 Linux 环境'},
    proof: [['架构', '渠道无关核心与适配器式投递'], ['记忆', 'AGENTS.md 与可观测的 SQLite 结构化记忆'], ['执行', '工具循环、原生与 ACP 子智能体、调度和后台任务'], ['扩展', '技能目录与 MCP 工具联邦']], whyTitle: '为什么团队选择 MicroClaw', whyText: '以运行时为中心，让渠道、模型和工具变化时核心逻辑依然稳定。',
    capabilities: [['渠道无关核心', '所有聊天和 Web 适配器共享同一个 agent loop。'], ['工具型 Agent Loop', '模型可以跨多个步骤连续调用工具，直到任务完成。'], ['并发专家团队', '具名专家子智能体可通过原生或 ACP Worker 并行工作。'], ['带质量门槛的记忆', '文件和 SQLite 记忆具备提取、去重和生命周期控制。'], ['技能 + MCP', '内置技能和外部 MCP Server 无需修改核心循环即可扩展能力。'], ['运维可见性', '用量、记忆观测、配置检查、指标和链路追踪让漂移可见。'], ['调度与后台任务', '周期任务和一次性任务都复用同一运行时。']], architectureTitle: '运行时架构一览', architectureText: '无论用户从哪里与智能体交流，背后都是同一个引擎。', architectureAlt: 'MicroClaw 架构概览', architectureSteps: [['接收', '渠道适配器把输入事件标准化为统一格式。'], ['组装上下文', '加载会话状态、记忆和已激活技能。'], ['推理与工具', 'Provider 层在受控循环中输出模型响应和工具调用。'], ['持久化与反思', '保存会话和记忆，并更新长期事实。'], ['投递', '按渠道限制分片，并以一致语义可靠投递。']], useCasesTitle: '用 MicroClaw 承载真实工作负载', useCasesText: '从个人运维到平台团队，一个运行时覆盖多种路径。', useCases: [['个人基础设施智能体', '在不同聊天中使用同一个具备记忆、调度和文件工具的助手。'], ['团队运维机器人', '使用权限感知工具和会话历史支持重复性内部流程。'], ['产品原型运行时', '在统一 Rust 核心上快速增加渠道和工具。']], readDetails: '查看实现细节', ctaTitle: '交付生产级 Rust 智能体技术栈。', ctaText: '从快速设置开始，再深入工具、权限、记忆和渠道部署。', quickstartCta: '快速开始', architectureDocs: '架构文档', toolsReference: '生成的工具参考',
  },
  hi: {
    tagline: 'Rust में बना आधुनिक संवाद माध्यमों के लिए agent runtime।', description: 'MicroClaw tools, memory, scheduling और MCP federation वाला Rust-first multi-channel agent runtime है।', eyebrow: 'RUST AGENT RUNTIME', heroTitle: 'एक agent core बनाएँ और उसे हर संवाद माध्यम पर चलाएँ।', heroText: 'MicroClaw durable memory, resumable sessions, subagents और साझा business logic वाले channel adapters के साथ tool-using automation देता है।', start: '5 मिनट में शुरू करें', github: 'GitHub देखें', meta: ['एक सेवा', 'SQLite persistence', 'ACP + MCP + Skills'], quickstart: 'त्वरित शुरुआत', copy: 'कॉपी', copied: 'कॉपी हुआ', installLabels: {script: 'इंस्टॉल स्क्रिप्ट', brew: 'Homebrew', cargo: 'Cargo', powershell: 'PowerShell स्क्रिप्ट'}, installHints: {macScript: 'अधिकांश macOS setups के लिए', brew: 'Homebrew workflows के लिए', source: 'Rust toolchain से source build', windowsScript: 'Native Windows install के लिए', linuxScript: 'अधिकांश Linux setups के लिए'},
    proof: [['आर्किटेक्चर', 'Adapter delivery वाला channel-independent core'], ['मेमोरी', 'AGENTS.md और observable SQLite memory'], ['एक्ज़ीक्यूशन', 'Tool loop, subagents, scheduling और background work'], ['एक्सटेंशन', 'Skills catalog और MCP federation']], whyTitle: 'टीम MicroClaw क्यों चुनती हैं', whyText: 'Channels, models और tools बदलें, फिर भी core logic स्थिर रहे।', capabilities: [['Channel-Independent Core', 'सभी chat और Web adapters एक agent loop साझा करते हैं।'], ['Tool-Using Agent Loop', 'मॉडल कार्य पूरा होने तक कई चरणों में tools चलाता है।'], ['Concurrent Specialist Team', 'विशेषज्ञ subagents native या ACP workers से समानांतर काम करते हैं।'], ['Quality-Gated Memory', 'File और SQLite memory में extraction, dedupe और lifecycle control हैं।'], ['Skills + MCP', 'Skills और MCP servers core loop बदले बिना क्षमता बढ़ाते हैं।'], ['Operational Visibility', 'Usage, config checks, metrics और traces drift दिखाते हैं।'], ['Scheduler + Background Tasks', 'Recurring और one-shot tasks उसी runtime में चलते हैं।']], architectureTitle: 'Runtime architecture एक नज़र में', architectureText: 'उपयोगकर्ता कहीं भी बात करें, engine एक ही रहता है।', architectureAlt: 'MicroClaw architecture', architectureSteps: [['इनजेस्ट', 'Adapters incoming events को एक format में बदलते हैं।'], ['कॉन्टेक्स्ट', 'Session, memory और active skills लोड होते हैं।'], ['Reason + Tools', 'Provider layer नियंत्रित loop में output और tool calls stream करती है।'], ['Persist + Reflect', 'Sessions और memory सुरक्षित होकर durable facts update होते हैं।'], ['डिलीवर', 'Channel limits के अनुसार परिणाम reliably भेजे जाते हैं।']], useCasesTitle: 'वास्तविक workloads के लिए MicroClaw', useCasesText: 'व्यक्तिगत operators से platform teams तक, एक runtime कई रास्ते संभालता है।', useCases: [['Personal Infra Agent', 'Memory, scheduling और file tools वाला एक assistant सभी chats में चलाएँ।'], ['Team Operations Bot', 'Permission-aware tools से recurring workflows चलाएँ।'], ['Product Prototyping Runtime', 'एक Rust core पर नए channels और tools ship करें।']], readDetails: 'Implementation details पढ़ें', ctaTitle: 'Production-grade Rust agent stack ship करें।', ctaText: 'Setup से शुरू करें, फिर tools, permissions, memory और channels देखें।', quickstartCta: 'Quickstart', architectureDocs: 'Architecture Docs', toolsReference: 'Generated Tools Reference',
  },
  es: {
    tagline: 'Runtime de agentes para interfaces de conversación modernas, creado en Rust.', description: 'MicroClaw es un runtime Rust para automatización multicanal con herramientas, memoria, programación y MCP.', eyebrow: 'RUNTIME DE AGENTES EN RUST', heroTitle: 'Crea un solo núcleo de agente y despliégalo en cada interfaz.', heroText: 'MicroClaw ofrece herramientas, memoria duradera, sesiones reanudables, subagentes y adaptadores que no duplican la lógica central.', start: 'Empieza en 5 minutos', github: 'Ver GitHub', meta: ['Un solo servicio', 'Persistencia SQLite', 'ACP + MCP + Skills'], quickstart: 'Inicio rápido', copy: 'Copiar', copied: 'Copiado', installLabels: {script: 'Script de instalación', brew: 'Homebrew', cargo: 'Cargo', powershell: 'Script de PowerShell'}, installHints: {macScript: 'Recomendado para la mayoría de instalaciones macOS', brew: 'Ideal para flujos con Homebrew', source: 'Compila desde el código fuente con Rust', windowsScript: 'Recomendado para Windows nativo', linuxScript: 'Recomendado para la mayoría de instalaciones Linux'},
    proof: [['Arquitectura', 'Núcleo independiente del canal y entrega mediante adaptadores'], ['Memoria', 'AGENTS.md y memoria SQLite observable'], ['Ejecución', 'Herramientas, subagentes, programación y tareas en segundo plano'], ['Extensión', 'Catálogo de skills y federación MCP']], whyTitle: 'Por qué los equipos eligen MicroClaw', whyText: 'Una arquitectura centrada en el runtime que mantiene estable tu lógica.', capabilities: [['Núcleo independiente del canal', 'Un solo bucle impulsa todos los adaptadores de chat y Web.'], ['Agente con herramientas', 'El modelo encadena herramientas hasta completar la tarea.'], ['Equipo de especialistas', 'Subagentes especializados trabajan en paralelo de forma nativa o mediante ACP.'], ['Memoria con controles de calidad', 'La memoria en archivos y SQLite incluye extracción, deduplicación y ciclo de vida.'], ['Skills + MCP', 'Las skills y servidores MCP amplían el runtime sin cambiar el núcleo.'], ['Visibilidad operativa', 'Uso, comprobaciones, métricas y trazas hacen visible la deriva.'], ['Programador y tareas', 'Las tareas periódicas y únicas usan el mismo runtime.']], architectureTitle: 'Arquitectura del runtime', architectureText: 'El mismo motor impulsa cada conversación, sin importar el canal.', architectureAlt: 'Arquitectura de MicroClaw', architectureSteps: [['Entrada', 'Los adaptadores normalizan los eventos entrantes.'], ['Contexto', 'Se cargan la sesión, la memoria y las skills activas.'], ['Razonamiento y herramientas', 'La capa de proveedor controla la salida y las llamadas a herramientas.'], ['Persistencia y reflexión', 'Se guardan sesiones y memoria y se actualizan hechos duraderos.'], ['Entrega', 'Los resultados se adaptan a los límites de cada canal.']], useCasesTitle: 'MicroClaw para cargas reales', useCasesText: 'Desde operadores individuales hasta equipos de plataforma.', useCases: [['Agente de infraestructura personal', 'Un asistente en todos tus chats con memoria, programación y herramientas.'], ['Bot de operaciones', 'Herramientas con permisos e historial para flujos internos.'], ['Runtime para prototipos', 'Nuevos canales y herramientas sobre un único núcleo Rust.']], readDetails: 'Ver detalles de implementación', ctaTitle: 'Entrega una plataforma de agentes Rust lista para producción.', ctaText: 'Empieza por la configuración y continúa con herramientas, permisos, memoria y canales.', quickstartCta: 'Inicio rápido', architectureDocs: 'Documentación de arquitectura', toolsReference: 'Referencia de herramientas',
  },
  ar: {
    tagline: 'بيئة تشغيل للوكلاء على واجهات المحادثة الحديثة، مبنية بلغة Rust.', description: 'MicroClaw بيئة Rust متعددة القنوات مزودة بالأدوات والذاكرة والجدولة وMCP.', eyebrow: 'بيئة وكلاء بلغة RUST', heroTitle: 'ابنِ نواة وكيل واحدة وانشرها على كل واجهات المحادثة.', heroText: 'يوفر MicroClaw أدوات وذاكرة دائمة وجلسات قابلة للاستئناف ووكلاء فرعيين ومحولات لا تكرر منطق العمل.', start: 'ابدأ خلال 5 دقائق', github: 'عرض GitHub', meta: ['خدمة واحدة', 'تخزين SQLite', 'ACP + MCP + المهارات'], quickstart: 'البدء السريع', copy: 'نسخ', copied: 'تم النسخ', installLabels: {script: 'برنامج التثبيت', brew: 'Homebrew', cargo: 'Cargo', powershell: 'برنامج PowerShell'}, installHints: {macScript: 'موصى به لمعظم أجهزة macOS', brew: 'مناسب لمسارات Homebrew', source: 'البناء من المصدر باستخدام Rust', windowsScript: 'موصى به لتثبيت Windows الأصلي', linuxScript: 'موصى به لمعظم أنظمة Linux'},
    proof: [['البنية', 'نواة مستقلة عن القناة وتسليم عبر المحولات'], ['الذاكرة', 'AGENTS.md وذاكرة SQLite قابلة للمراقبة'], ['التنفيذ', 'حلقة أدوات ووكلاء فرعيون وجدولة وعمل خلفي'], ['التوسعة', 'فهرس مهارات واتحاد أدوات MCP']], whyTitle: 'لماذا تختار الفرق MicroClaw', whyText: 'نظام يتمحور حول بيئة التشغيل ويحافظ على ثبات منطقك.', capabilities: [['نواة مستقلة عن القناة', 'حلقة وكيل واحدة لكل محولات المحادثة والويب.'], ['وكيل يستخدم الأدوات', 'يربط النموذج الأدوات عبر خطوات متعددة حتى اكتمال المهمة.'], ['فريق متخصص متزامن', 'يعمل الوكلاء المتخصصون بالتوازي محليًا أو عبر ACP.'], ['ذاكرة بضوابط جودة', 'تتضمن ذاكرة الملفات وSQLite الاستخراج وإزالة التكرار ودورة الحياة.'], ['المهارات + MCP', 'توسّع المهارات وخوادم MCP القدرات من دون تغيير النواة.'], ['رؤية تشغيلية', 'تكشف تقارير الاستخدام والفحوص والمقاييس والتتبع الانحراف.'], ['الجدولة والمهام', 'تعمل المهام الدورية والمؤقتة عبر البيئة نفسها.']], architectureTitle: 'بنية التشغيل في لمحة', architectureText: 'المحرك نفسه يشغّل كل محادثة أينما كان المستخدم.', architectureAlt: 'بنية MicroClaw', architectureSteps: [['الاستقبال', 'توحّد محولات القنوات الأحداث الواردة.'], ['تجميع السياق', 'تُحمّل الجلسة والذاكرة والمهارات النشطة.'], ['الاستدلال والأدوات', 'تدير طبقة المزوّد المخرجات واستدعاءات الأدوات.'], ['الحفظ والتأمل', 'تُحفظ الجلسات والذاكرة وتُحدّث الحقائق الدائمة.'], ['التسليم', 'تُكيّف النتائج مع حدود القنوات وتُسلّم باتساق.']], useCasesTitle: 'استخدم MicroClaw للأعمال الحقيقية', useCasesText: 'من المشغل الفردي إلى فرق المنصات.', useCases: [['وكيل بنية تحتية شخصي', 'مساعد واحد في محادثاتك مع الذاكرة والجدولة والأدوات.'], ['روبوت عمليات الفريق', 'أدوات واعية بالصلاحيات وسجل للجلسات المتكررة.'], ['بيئة للنماذج الأولية', 'أضف قنوات وأدوات جديدة فوق نواة Rust واحدة.']], readDetails: 'قراءة تفاصيل التنفيذ', ctaTitle: 'أطلق منصة وكلاء Rust جاهزة للإنتاج.', ctaText: 'ابدأ بالإعداد ثم استكشف الأدوات والصلاحيات والذاكرة والقنوات.', quickstartCta: 'البدء السريع', architectureDocs: 'وثائق البنية', toolsReference: 'مرجع الأدوات',
  },
  fr: {
    tagline: "Runtime d'agents pour les interfaces de conversation modernes, écrit en Rust.", description: 'MicroClaw est un runtime Rust multicanal avec outils, mémoire, planification et fédération MCP.', eyebrow: "RUNTIME D'AGENTS RUST", heroTitle: "Créez un seul cœur d'agent et déployez-le sur chaque interface.", heroText: "MicroClaw fournit outils, mémoire durable, sessions récupérables, sous-agents et adaptateurs sans dupliquer la logique métier.", start: 'Démarrer en 5 minutes', github: 'Voir GitHub', meta: ['Un seul service', 'Persistance SQLite', 'ACP + MCP + Skills'], quickstart: 'Démarrage rapide', copy: 'Copier', copied: 'Copié', installLabels: {script: "Script d'installation", brew: 'Homebrew', cargo: 'Cargo', powershell: 'Script PowerShell'}, installHints: {macScript: 'Recommandé pour la plupart des installations macOS', brew: 'Idéal pour les flux Homebrew', source: 'Compiler depuis les sources avec Rust', windowsScript: 'Recommandé pour Windows natif', linuxScript: 'Recommandé pour la plupart des installations Linux'},
    proof: [['Architecture', 'Cœur indépendant du canal et livraison par adaptateurs'], ['Mémoire', 'AGENTS.md et mémoire SQLite observable'], ['Exécution', 'Outils, sous-agents, planification et tâches de fond'], ['Extension', 'Catalogue de skills et fédération MCP']], whyTitle: 'Pourquoi les équipes choisissent MicroClaw', whyText: 'Une pile centrée sur le runtime qui garde votre logique stable.', capabilities: [['Cœur indépendant du canal', 'Une boucle partagée alimente tous les adaptateurs de chat et Web.'], ['Agent utilisant des outils', "Le modèle enchaîne les outils jusqu'à la fin de la tâche."], ['Équipe de spécialistes', 'Des sous-agents spécialisés travaillent en parallèle, nativement ou via ACP.'], ['Mémoire avec contrôle qualité', 'La mémoire fichier et SQLite gère extraction, déduplication et cycle de vie.'], ['Skills + MCP', 'Les skills et serveurs MCP étendent le runtime sans changer le cœur.'], ['Visibilité opérationnelle', "Utilisation, contrôles, métriques et traces rendent les dérives visibles."], ['Planification et tâches', 'Les tâches récurrentes et ponctuelles utilisent le même runtime.']], architectureTitle: "Vue d'ensemble de l'architecture", architectureText: 'Le même moteur alimente chaque conversation, quel que soit le canal.', architectureAlt: 'Architecture de MicroClaw', architectureSteps: [['Entrée', 'Les adaptateurs normalisent les événements entrants.'], ['Contexte', 'La session, la mémoire et les skills actives sont chargées.'], ['Raisonnement et outils', 'La couche fournisseur contrôle les sorties et appels aux outils.'], ['Persistance et réflexion', 'Sessions et mémoire sont sauvegardées, puis les faits mis à jour.'], ['Livraison', 'Les résultats respectent les limites de chaque canal.']], useCasesTitle: 'MicroClaw pour des charges réelles', useCasesText: "De l'opérateur individuel aux équipes plateforme.", useCases: [['Agent d’infrastructure personnel', 'Un assistant dans tous vos chats avec mémoire, planification et outils.'], ["Bot d'opérations d'équipe", "Des outils tenant compte des droits pour les flux internes."], ['Runtime de prototypage', 'Ajoutez canaux et outils sur un seul cœur Rust.']], readDetails: "Voir les détails d'implémentation", ctaTitle: "Livrez une plateforme d'agents Rust prête pour la production.", ctaText: 'Commencez par la configuration, puis explorez outils, droits, mémoire et canaux.', quickstartCta: 'Démarrage rapide', architectureDocs: "Documentation d'architecture", toolsReference: 'Référence des outils',
  },
  bn: {
    tagline: 'Rust-এ তৈরি আধুনিক কথোপকথনের জন্য agent runtime।', description: 'MicroClaw হলো tools, memory, scheduling এবং MCP-সহ Rust-first multi-channel runtime।', eyebrow: 'RUST AGENT RUNTIME', heroTitle: 'একটি agent core তৈরি করুন, সব কথোপকথন মাধ্যমে চালান।', heroText: 'MicroClaw tool automation, durable memory, resumable session, subagent এবং একই business logic ব্যবহারকারী adapter দেয়।', start: '৫ মিনিটে শুরু', github: 'GitHub দেখুন', meta: ['একটি service', 'SQLite persistence', 'ACP + MCP + Skills'], quickstart: 'দ্রুত শুরু', copy: 'কপি', copied: 'কপি হয়েছে', installLabels: {script: 'Install Script', brew: 'Homebrew', cargo: 'Cargo', powershell: 'PowerShell Script'}, installHints: {macScript: 'বেশিরভাগ macOS setup-এর জন্য', brew: 'Homebrew workflow-এর জন্য', source: 'Rust toolchain দিয়ে source build', windowsScript: 'Native Windows install-এর জন্য', linuxScript: 'বেশিরভাগ Linux setup-এর জন্য'},
    proof: [['আর্কিটেকচার', 'Adapter delivery-সহ channel-independent core'], ['মেমরি', 'AGENTS.md ও observable SQLite memory'], ['এক্সিকিউশন', 'Tool loop, subagent, scheduling ও background work'], ['এক্সটেনশন', 'Skills catalog ও MCP federation']], whyTitle: 'দলগুলো কেন MicroClaw বেছে নেয়', whyText: 'Channel, model ও tool বদলালেও core logic স্থিতিশীল থাকে।', capabilities: [['Channel-Independent Core', 'সব chat ও Web adapter একটি agent loop ব্যবহার করে।'], ['Tool-Using Agent Loop', 'Task শেষ না হওয়া পর্যন্ত model একাধিক ধাপে tool চালায়।'], ['Concurrent Specialist Team', 'বিশেষজ্ঞ subagent native বা ACP-তে সমান্তরালে কাজ করে।'], ['Quality-Gated Memory', 'File ও SQLite memory-তে extraction, dedupe ও lifecycle control আছে।'], ['Skills + MCP', 'Skills ও MCP server core loop না বদলে ক্ষমতা বাড়ায়।'], ['Operational Visibility', 'Usage, checks, metrics ও traces drift দৃশ্যমান করে।'], ['Scheduler + Background Tasks', 'Recurring ও one-shot task একই runtime ব্যবহার করে।']], architectureTitle: 'Runtime architecture এক নজরে', architectureText: 'ব্যবহারকারী যেখানেই কথা বলুক, engine একই।', architectureAlt: 'MicroClaw architecture', architectureSteps: [['ইনজেস্ট', 'Adapter incoming event-কে এক format-এ আনে।'], ['কনটেক্সট', 'Session, memory ও active skill লোড হয়।'], ['Reason + Tools', 'Provider layer নিয়ন্ত্রিত loop-এ output ও tool call চালায়।'], ['Persist + Reflect', 'Session ও memory সংরক্ষণ করে durable fact update হয়।'], ['ডেলিভারি', 'Channel limit অনুযায়ী ফল নির্ভরযোগ্যভাবে পাঠানো হয়।']], useCasesTitle: 'বাস্তব workload-এর জন্য MicroClaw', useCasesText: 'ব্যক্তিগত operator থেকে platform team পর্যন্ত।', useCases: [['Personal Infra Agent', 'সব chat-এ memory, scheduling ও file tool-সহ assistant।'], ['Team Operations Bot', 'Permission-aware tool দিয়ে recurring workflow।'], ['Product Prototyping Runtime', 'এক Rust core-এ নতুন channel ও tool যোগ করুন।']], readDetails: 'Implementation details পড়ুন', ctaTitle: 'Production-grade Rust agent stack চালু করুন।', ctaText: 'Setup দিয়ে শুরু করে tools, permissions, memory ও channel দেখুন।', quickstartCta: 'Quickstart', architectureDocs: 'Architecture Docs', toolsReference: 'Generated Tools Reference',
  },
  pt: {
    tagline: 'Runtime de agentes para interfaces de conversa modernas, criado em Rust.', description: 'MicroClaw é um runtime Rust multicanal com ferramentas, memória, agendamento e MCP.', eyebrow: 'RUNTIME DE AGENTES EM RUST', heroTitle: 'Crie um único núcleo de agente e implante-o em cada interface.', heroText: 'MicroClaw oferece ferramentas, memória durável, sessões retomáveis, subagentes e adaptadores sem duplicar a lógica central.', start: 'Comece em 5 minutos', github: 'Ver GitHub', meta: ['Um único serviço', 'Persistência SQLite', 'ACP + MCP + Skills'], quickstart: 'Início rápido', copy: 'Copiar', copied: 'Copiado', installLabels: {script: 'Script de instalação', brew: 'Homebrew', cargo: 'Cargo', powershell: 'Script PowerShell'}, installHints: {macScript: 'Recomendado para a maioria dos Macs', brew: 'Ideal para fluxos com Homebrew', source: 'Compile do código-fonte com Rust', windowsScript: 'Recomendado para Windows nativo', linuxScript: 'Recomendado para a maioria dos Linux'},
    proof: [['Arquitetura', 'Núcleo independente de canal e entrega por adaptadores'], ['Memória', 'AGENTS.md e memória SQLite observável'], ['Execução', 'Ferramentas, subagentes, agendamento e tarefas em segundo plano'], ['Extensão', 'Catálogo de skills e federação MCP']], whyTitle: 'Por que as equipes escolhem MicroClaw', whyText: 'Uma pilha centrada no runtime que mantém sua lógica estável.', capabilities: [['Núcleo independente de canal', 'Um único loop alimenta todos os adaptadores de chat e Web.'], ['Agente com ferramentas', 'O modelo encadeia ferramentas até concluir a tarefa.'], ['Equipe de especialistas', 'Subagentes especializados trabalham em paralelo, nativamente ou via ACP.'], ['Memória com controle de qualidade', 'Memória em arquivos e SQLite com extração, deduplicação e ciclo de vida.'], ['Skills + MCP', 'Skills e servidores MCP ampliam o runtime sem alterar o núcleo.'], ['Visibilidade operacional', 'Uso, verificações, métricas e traces tornam desvios visíveis.'], ['Agendamento e tarefas', 'Tarefas recorrentes e únicas usam o mesmo runtime.']], architectureTitle: 'Arquitetura do runtime', architectureText: 'O mesmo mecanismo alimenta cada conversa, em qualquer canal.', architectureAlt: 'Arquitetura do MicroClaw', architectureSteps: [['Entrada', 'Adaptadores normalizam eventos recebidos.'], ['Contexto', 'Sessão, memória e skills ativas são carregadas.'], ['Raciocínio e ferramentas', 'A camada do provedor controla saídas e ferramentas.'], ['Persistência e reflexão', 'Sessões e memória são salvas e fatos duráveis atualizados.'], ['Entrega', 'Resultados respeitam os limites de cada canal.']], useCasesTitle: 'MicroClaw para cargas reais', useCasesText: 'De operadores individuais a equipes de plataforma.', useCases: [['Agente de infraestrutura pessoal', 'Um assistente em todos os chats com memória, agendamento e ferramentas.'], ['Bot de operações', 'Ferramentas com permissões para fluxos internos recorrentes.'], ['Runtime para protótipos', 'Novos canais e ferramentas sobre um único núcleo Rust.']], readDetails: 'Ver detalhes da implementação', ctaTitle: 'Entregue uma plataforma de agentes Rust pronta para produção.', ctaText: 'Comece pela configuração e explore ferramentas, permissões, memória e canais.', quickstartCta: 'Início rápido', architectureDocs: 'Documentação de arquitetura', toolsReference: 'Referência de ferramentas',
  },
  id: {
    tagline: 'Runtime agen untuk antarmuka percakapan modern, dibangun dengan Rust.', description: 'MicroClaw adalah runtime Rust multichannel dengan tools, memory, penjadwalan, dan MCP.', eyebrow: 'RUNTIME AGEN RUST', heroTitle: 'Bangun satu inti agen dan jalankan di setiap antarmuka.', heroText: 'MicroClaw menyediakan tools, memory tahan gangguan, sesi yang dapat dilanjutkan, subagent, dan adapter tanpa menduplikasi logika inti.', start: 'Mulai dalam 5 menit', github: 'Lihat GitHub', meta: ['Satu layanan', 'Persistensi SQLite', 'ACP + MCP + Skills'], quickstart: 'Mulai cepat', copy: 'Salin', copied: 'Tersalin', installLabels: {script: 'Skrip instalasi', brew: 'Homebrew', cargo: 'Cargo', powershell: 'Skrip PowerShell'}, installHints: {macScript: 'Disarankan untuk sebagian besar macOS', brew: 'Cocok untuk alur Homebrew', source: 'Build dari source dengan Rust', windowsScript: 'Disarankan untuk Windows native', linuxScript: 'Disarankan untuk sebagian besar Linux'},
    proof: [['Arsitektur', 'Inti independen channel dengan pengiriman berbasis adapter'], ['Memory', 'AGENTS.md dan memory SQLite yang dapat diamati'], ['Eksekusi', 'Tool loop, subagent, penjadwalan, dan tugas latar'], ['Ekstensi', 'Katalog skills dan federasi MCP']], whyTitle: 'Mengapa tim memilih MicroClaw', whyText: 'Stack berpusat pada runtime yang menjaga logika tetap stabil.', capabilities: [['Inti independen channel', 'Satu agent loop untuk semua adapter chat dan Web.'], ['Agent dengan tools', 'Model merangkai tools sampai tugas selesai.'], ['Tim spesialis', 'Subagent spesialis bekerja paralel secara native atau melalui ACP.'], ['Memory dengan quality gate', 'Memory file dan SQLite memiliki ekstraksi, deduplikasi, dan lifecycle.'], ['Skills + MCP', 'Skills dan MCP server memperluas runtime tanpa mengubah inti.'], ['Visibilitas operasional', 'Usage, pemeriksaan, metrics, dan traces menampilkan drift.'], ['Penjadwal dan tugas', 'Tugas berulang dan sekali jalan memakai runtime yang sama.']], architectureTitle: 'Arsitektur runtime sekilas', architectureText: 'Engine yang sama menjalankan setiap percakapan di semua channel.', architectureAlt: 'Arsitektur MicroClaw', architectureSteps: [['Masuk', 'Adapter menormalkan event yang masuk.'], ['Susun konteks', 'Sesi, memory, dan skills aktif dimuat.'], ['Reason + Tools', 'Lapisan provider mengendalikan output dan tool call.'], ['Simpan + Refleksi', 'Sesi dan memory disimpan lalu fakta diperbarui.'], ['Kirim', 'Hasil mengikuti batas setiap channel secara konsisten.']], useCasesTitle: 'MicroClaw untuk workload nyata', useCasesText: 'Dari operator individu sampai tim platform.', useCases: [['Agen infrastruktur pribadi', 'Satu asisten di semua chat dengan memory, jadwal, dan tools.'], ['Bot operasi tim', 'Tools berbasis izin untuk workflow internal berulang.'], ['Runtime prototipe produk', 'Tambahkan channel dan tools pada satu inti Rust.']], readDetails: 'Baca detail implementasi', ctaTitle: 'Kirim stack agen Rust siap produksi.', ctaText: 'Mulai dari setup, lalu pelajari tools, izin, memory, dan channel.', quickstartCta: 'Mulai cepat', architectureDocs: 'Dokumentasi arsitektur', toolsReference: 'Referensi tools',
  },
  ur: {
    tagline: 'Rust میں بنایا گیا جدید گفتگو ذرائع کے لیے agent runtime۔', description: 'MicroClaw tools، memory، scheduling اور MCP والا Rust-first multi-channel runtime ہے۔', eyebrow: 'RUST AGENT RUNTIME', heroTitle: 'ایک agent core بنائیں اور ہر گفتگو ذریعے پر چلائیں۔', heroText: 'MicroClaw durable memory، resumable sessions، subagents اور مشترک business logic والے adapters کے ساتھ tool automation دیتا ہے۔', start: '5 منٹ میں شروع کریں', github: 'GitHub دیکھیں', meta: ['ایک service', 'SQLite persistence', 'ACP + MCP + Skills'], quickstart: 'فوری آغاز', copy: 'کاپی', copied: 'کاپی ہو گیا', installLabels: {script: 'Install Script', brew: 'Homebrew', cargo: 'Cargo', powershell: 'PowerShell Script'}, installHints: {macScript: 'زیادہ تر macOS setups کے لیے', brew: 'Homebrew workflows کے لیے', source: 'Rust toolchain سے source build', windowsScript: 'Native Windows install کے لیے', linuxScript: 'زیادہ تر Linux setups کے لیے'},
    proof: [['آرکیٹیکچر', 'Adapter delivery والا channel-independent core'], ['میموری', 'AGENTS.md اور observable SQLite memory'], ['عمل', 'Tool loop، subagents، scheduling اور background work'], ['توسیع', 'Skills catalog اور MCP federation']], whyTitle: 'ٹیمیں MicroClaw کیوں منتخب کرتی ہیں', whyText: 'Channels، models اور tools بدلیں مگر core logic مستحکم رہے۔', capabilities: [['Channel-Independent Core', 'تمام chat اور Web adapters ایک agent loop استعمال کرتے ہیں۔'], ['Tool-Using Agent Loop', 'Task مکمل ہونے تک model کئی مراحل میں tools چلاتا ہے۔'], ['Concurrent Specialist Team', 'ماہر subagents native یا ACP کے ذریعے متوازی کام کرتے ہیں۔'], ['Quality-Gated Memory', 'File اور SQLite memory میں extraction، dedupe اور lifecycle control ہے۔'], ['Skills + MCP', 'Skills اور MCP servers core loop بدلے بغیر صلاحیت بڑھاتے ہیں۔'], ['Operational Visibility', 'Usage، checks، metrics اور traces drift دکھاتے ہیں۔'], ['Scheduler + Background Tasks', 'Recurring اور one-shot tasks اسی runtime میں چلتے ہیں۔']], architectureTitle: 'Runtime architecture ایک نظر میں', architectureText: 'صارف کہیں بھی بات کریں، engine ایک ہی رہتا ہے۔', architectureAlt: 'MicroClaw architecture', architectureSteps: [['انجیسٹ', 'Adapters incoming events کو ایک format میں لاتے ہیں۔'], ['سیاق', 'Session، memory اور active skills لوڈ ہوتے ہیں۔'], ['Reason + Tools', 'Provider layer controlled loop میں output اور tool calls چلاتی ہے۔'], ['Persist + Reflect', 'Sessions اور memory محفوظ ہو کر durable facts update ہوتے ہیں۔'], ['ترسیل', 'Channel limits کے مطابق نتائج reliably بھیجے جاتے ہیں۔']], useCasesTitle: 'حقیقی workloads کے لیے MicroClaw', useCasesText: 'ذاتی operators سے platform teams تک۔', useCases: [['Personal Infra Agent', 'تمام chats میں memory، scheduling اور file tools والا assistant۔'], ['Team Operations Bot', 'Permission-aware tools سے recurring workflows۔'], ['Product Prototyping Runtime', 'ایک Rust core پر نئے channels اور tools شامل کریں۔']], readDetails: 'Implementation details پڑھیں', ctaTitle: 'Production-grade Rust agent stack جاری کریں۔', ctaText: 'Setup سے شروع کریں، پھر tools، permissions، memory اور channels دیکھیں۔', quickstartCta: 'Quickstart', architectureDocs: 'Architecture Docs', toolsReference: 'Generated Tools Reference',
  },
}

export function getHomeMessages(locale) {
  return translations[locale] || en;
}
